# Generated by Django 4.2.11 on 2024-05-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('producto_nombre', models.CharField(max_length=100)),
                ('producto_descripcion', models.TextField()),
                ('producto_imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('producto_precio', models.PositiveIntegerField()),
                ('producto_inventario', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idservicio', models.AutoField(primary_key=True, serialize=False)),
                ('servicio_nombre', models.CharField(max_length=100)),
                ('servicio_descripcion', models.TextField()),
                ('servicio_imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('servicio_precio', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('venta_fecha', models.DateField()),
                ('venta_total', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('iddetalleventa', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_cantidad', models.PositiveIntegerField()),
                ('detalle_precio', models.PositiveIntegerField()),
                ('idproducto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_negocio.producto')),
                ('idservicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_negocio.servicio')),
                ('idventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_negocio.venta')),
            ],
        ),
    ]
