# Generated by Django 4.2.11 on 2024-05-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_negocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='servicio_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
