# Generated by Django 4.2.3 on 2024-12-13 02:51

from django.db import migrations, models
import proyecto_negocio.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_negocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacante',
            options={'verbose_name': 'Vacante', 'verbose_name_plural': 'Vacantes'},
        ),
        migrations.AlterField(
            model_name='vacante',
            name='codigo_vacante',
            field=models.CharField(default=proyecto_negocio.models.generate_unique_codigo, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='numero_puestos',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
